### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ankushgoel27** [Shellntel/luckystrike#1]
Hi,

I get this error when i try to run the script. i tried both regular and admin command prompts.

C:\Windows\system32>powershell
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> iex (new-object net.webclient).downloadstring('https://r
aw.githubusercontent.com/Shellntel/luckystrike/master/install.ps1')
### LUCKYSTRIKE INSTALLATION ROUTINE ###
[*] Installing\Importing Dependencies..
[*] Module (PSSQlite) not found, attempting to install and import.
iex (new-object net.webclient).downloadstring('https://raw.githubusercontent.co
m/Shellntel/luckystrike/master/install.ps1') : [!] Module install/import error!
 Attempt to manually install PSSQlite
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n

**Comment by curi0usJack** [comment]
hmm - from an administrative PS prompt, what happens if you run "Install-Module PSSQLite"?
Are you on PS V5?

**Comment by c0mrad** [comment]
Try this: Set-ExecutionPolicy -ExecutionPolicy Unrestricted

**Comment by ankushgoel27** [comment]
i did couple of things to fix the issue. 

First, upgraded my powershell to 5.0.
Then, i installed the PsGet Module
Then, i installed the PSSQLITE module manually in the powershell module folder.
Now, i have to import the pssqlite module every time i run the luckystrike script.

**Comment by ankushgoel27** [comment]
"Install-Module PSSQLite" - it is throwing an error saying this module was not found in central Repository

**Comment by curi0usJack** [comment]
I'm not using the Install-Module that comes with PsGet, but the one that comes with PowerShell v5.  I think you foobar'd things by installing PsGet on top of PowerShell v5. Please remove PsGet & see if you can run Install-Module PSSQLite.

**Comment by ankushgoel27** [comment]
i re-installed my powershell and it works fine now. You can close this issue. Thanks for the help :)

**Comment by curi0usJack** [comment]
Great to hear.
