### ISSUE TITLE
Exe Payload - VBA Compile Error

### ISSUE THREAD

**Issue by jongoodgion** [Shellntel/luckystrike#10]
Saw you guys at DerbyCon and had to try this out!! Thanks for your hard work.

Was wondering if you could help with a compile error I'm getting... I installed and used luckystrike on Win10 x64 to inject an exe via disk, generating new xls file. Then I was testing opening it on Win7 x64 box using Excel 2013 (the Win10 box also had Office 2013 and is generating the same compile syntax error). But when I click enable macro, the VBA code is throwing the error. I'm not familiar with VBA - is there something I'm doing wrong? Your help is appreciated!

![screen shot 2016-10-05 at 3 38 52 pm](https://cloud.githubusercontent.com/assets/12418879/19128588/058fb670-8b12-11e6-83e5-8b1d21a9989b.png)

**Comment by notsoluckystrike** [comment]
They fucked up with commas. I diffed luckystrike.ps1 that worked against the master version - saw nothing regarding commas. Btw, all VBA code is corrupted, so the tool is broken now. I don't know why they pushed invalid code into master. Дебилы блять.

**Comment by curi0usJack** [comment]
@notsoluckystrike wow - you're right! Those idiot devs. It's almost as if it's only one guy who has to maintain all that code on his free time while trying to maintain a work-life balance! I'll have a chat with them & see what can be done to reprioritize their lives.

@jongoodgion - thanks for the screenshot. You're not doing anything wrong. I moved everything to an auto-updating format so it was complicated to say the least. I should be able to get a fix out this evening. You'll be the first one to test the new auto-update. :-)

**Comment by kxyne** [comment]
Issue cause is (I think) the escaped "'s in the DB file which aren't intrepreted when they get used in the PS.

https://github.com/Shellntel/luckystrike/blob/master/db.sql

**Comment by curi0usJack** [comment]
right you are. previously the sql was in a powershell here-string which necessitated the escapes, but I took that out for 1.1.6. Fix seemed simple enough (just remove the escape characters), but that seemed to create other problems. I'm going to do a quick test and see if I can roll 1.1.7 via auto update, but if that doesn't work, I'll have no choice but to revert to 1.1.5 until I get this mess sorted out.

**Comment by kxyne** [comment]
oh, and can you `git push origin --tags` please :)

**Comment by curi0usJack** [comment]
ok, I think master is "fixed" for the moment. The auto-update feature is borked and requires major rework, so I can't distribute the fix via auto update. Unfortunately, the only way to get this fix in is to trash the luckystrike directory & reinstall via install.ps1. I tested all payload types and things seem to be working well.

*Really* sorry for the headache. Every time I use git I feel like a tard, and this is just highlighting all  the things I don't know about good version control. I'd highly recommend you don't fork master until I can get this under control.

**Comment by curi0usJack** [comment]
allright, I think I got this sorted out. @jongoodgion @kxyne - would you guys be willing to try something for me please? 

1. Ensure you are running 1.1.6. 
2. Make a backup of your luckystrike directory.
3. Open luckystrike.ps1 and do a find & replace, changing "master" to "dev".
4. Run luckystrike.ps1. You should be prompted to update. Hit Y.
5. The update sequence should launch & run successfully. 
6. Run luckystrike. You should be at 1.1.7 with your payloads still in the db.

So far, everything has worked in my testing, but well.... it usually works on my machine. =)

Thanks in advance!

**Comment by kxyne** [comment]
hadn't seen the issue mention (mail filter), I'll endeavour to try it on a few boxes today.

**Comment by curi0usJack** [comment]
Fix has been implemented in 1.1.7 which will be released shortly. To live on the bleeding edge, you can edit luckystrike.ps1 and find/replace "/master/" with "/dev/"
