### ISSUE TITLE
Run-Time Error '5': Invalid procedure call or argument with Certutil

### ISSUE THREAD

**Issue by thezoid** [Shellntel/luckystrike#12]
When I use certutil, it always errors this, and the payload does not execute, as it breaks on Shell (expath)

I am running Excel 2013
<img src="https://i.imgur.com/469DK8X.png" alt="error" />
<img src="https://i.imgur.com/xeWhQsn.png" alt="excel version"/>

There also lacks documentation on what each infection method does

When I try save to disk, it has worked before, but now I get:
<img src="https://i.imgur.com/aFaNorO.png" alt="error-2" />

**Comment by curi0usJack** [comment]
Your first two screenshots didn't come through. If you press 98 when choosing an infection method, it will give you an idea of what is being performed. 

In this case, it's trying to save the file to the Application.UserLibraryPath variable, which in Excel is usually %AppData%\Roaming\Microsoft\AddIns. Does that directory exist?

**Comment by thezoid** [comment]
aah okay, I always assumed that was a back button. Sort of vague. Thanks. I don't know what changed but I got it working, could be it just generated a few wrong files. I think changing the filename helped.

Those images appear to me, and are hosted by githubusercontent.

**Comment by curi0usJack** [comment]
99 is back. 98 is wtf. :-)

Glad to hear things are working. Feel free to open another issue if you run into problems.
