### ISSUE TITLE
VBA Run-time error '5'

### ISSUE THREAD

**Issue by Krysher** [Shellntel/luckystrike#14]
Enabling macro give me Run-Time error '5':
Invalid procedure call or argument.

I am using the dev branch because I keep running into the issue of out of memory. 
The debug problem is show at line "Shell (pth)"

Happen on both Save to disk and Centriul. Going to microsoft/addins, I do see both the execute file and the text file with encoded code in it.

I am using windows 10 and Microsoft excel 2016

**Comment by curi0usJack** [comment]
1) Have you confirmed your payload works?
2) How large is the .exe you're working with?
3) Are you able to get it to work in 1.1.7 (dev) without the out of memory error??
4) Please post a screenshot of the error (including the macro code).

**Comment by curi0usJack** [comment]
No response.
