### ISSUE TITLE
bypass method

### ISSUE THREAD

**Issue by PandoraSec** [Shellntel/luckystrike#18]
hi, how can i make fud the macros oradd my own bypass method to the payloads in lucky? cuz avast always detect all macros
Greetings, my friend

**Comment by curi0usJack** [comment]
So the good news is that Avast is really only one of two vendors that catch luckystrike payloads that I'm aware of (Kaspersky heuristics filter being the other one), but generally not used in enterprise environments. I add new infection types as I get time, but this is a personal project for me. 

You are always free to submit a PR if you have a new attack method to contribute. =)
