### ISSUE TITLE
 Math bug found. Parts length doesn't match numrows in legend

### ISSUE THREAD

**Issue by sergunz** [Shellntel/luckystrike#19]
Hi!
I try generate new xls file, and got error
[*] - Generating macro code.
[*] - Adding macro to workbook.
[*] - Embedding payloads into workbook.
[!] - Math bug found. Parts length doesn't match numrows in legend. Run in -Debug

In debug
[*] - Adding macro to workbook.
[DBG] - Executed Query: SELECT * FROM ActiveWorking. Params:
[*] - Embedding payloads into workbook.
[DBG] - Executed Query: SELECT * FROM Payloads WHERE ID = @id. Params: id:1
[!] - Math bug found. Parts length doesn't match numrows in legend. Run in -Debug

How can i fix this?
Thanks!

**Comment by curi0usJack** [comment]
Hey, sorry it's taken me so long to reply to this issue. I'm aware of the bug but haven't had time to troubleshoot it however. Out of curiosity, have you tried scrapping your ls.db file and reinstalling?

**Comment by curi0usJack** [comment]
@sergunz - do you get this with a powershell based payload by chance? If so, did you base64 encode it before adding it as a payload?

**Comment by curi0usJack** [comment]
k. found the problem. fixed in 1.1.7

**Comment by rami418** [comment]
Hi, first thanks for this framework :)

Having (exactly) the same issue with 1.1.7 using ps1 payload (generated by Empire) while selecting Cell Embed or Cell Embed-Encrypted. 

Working on win7 pro SP1 32bits

Any suggestion ?

Thanks ;)

**Comment by curi0usJack** [comment]
Hmm - do me a favor. Edit luckystrike.ps1 and do a find/replace: Change "/master/" to "/dev/". That will switch you over to the dev branch. You'll be prompted to update, hit Y.

Same error?

**Comment by rami418** [comment]
- The ps1 is working for Cell-Embed now, but the xls generated is showing an error : 

"'Execution error '-2147024690 (800700ce)' Method Run of Object 'IWshShell3' failed"
(i did traduce the error ;)

Did not find any satisfying solution :/

- For the Cell-Obfuscated (don't know i you have finished doing it !)
"Someting is wrong. Payload parts array is null when it shouldn't be. Was the payload successfully loaded in the database ?"

- One question : do you know an easy way to test the Cell-Encrypted on Virtual Machine ?


Thanks a lot
