### ISSUE TITLE
2 things help pls

### ISSUE THREAD

**Issue by c0mrad** [Shellntel/luckystrike#2]
The first problem i encountered was that i can't delete payloads. 

http://prntscr.com/cmpxcx

And the second problem when i try to generate the payload to a xls.

http://prntscr.com/cmpxxo

^^ sorry for the foreign language

**Comment by c0mrad** [comment]
Apparently excel can't get access to /luckystrike/payloads for some reason..

**Comment by curi0usJack** [comment]
I know what the first problem is (working on a fix). Can you translate the second error to English please?

**Comment by curi0usJack** [comment]
v1.1.1 has been pushed. fixed the PID error.

**Comment by c0mrad** [comment]
Great ! 
I will translate the second later today when i have watched the debate and get back home to my other pc.

**Comment by curi0usJack** [comment]
@c0mrad - re: your other message, glad to hear it's working. Hope you don't find it too harmless. ;-)
