### ISSUE TITLE
Invalid DocType (table) and $script:doctype variable is neverset.

### ISSUE THREAD

**Issue by psobject** [Shellntel/luckystrike#20]
It looks like the current version from the git is unusable, I've tried tracking down the error but
I couldn't really figure the root cause.

As it looks, `$script:doctype`is never set in this version, and  it seems impossible to create  a new doctype
for some reason. I've manually set `$script:doctype` and then tried adding a new file but got 
the following error:

```
Invoke-SqliteQuery : Exception calling "Fill" with "1" argument(s): "SQL logic error or missing database
no such table: Assoc_Infection_DocType"
At C:\luckystrike\luckystrike\luckystrike.ps1:205 char:17

+ ... tmpoutput = Invoke-SqliteQuery -SQLiteConnection $dbConnection -Query ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SqliteQuery

```

Can you take a look at it? I think I'll try using  `4a05b63aed687392cffe0e14e69256df3eb1eec3`
with hopes that it would just work there.

Note:
Since 1.1.7 only supports xls, the bug is fixed there, but makes it kind of less usable 👍 
What condition sets `$script:doctype`to a valid one? I couldn't find it in the code.

**Comment by curi0usJack** [comment]
Looks like you're using the dev branch, which is somewhat unusable right now yeah. I'm in the middle of adding support for Word payloads/templates. It's probably 75% there, but not exactly ready.

Have you tried using the master branch?

**Comment by psobject** [comment]
Nope, I'm using master.

**Comment by curi0usJack** [comment]
hmm - I don't see how. Nothing in master points to those vars or sqlite tables. Do me a favor, open the luckystrike.ps1 file and send me a screenshot of lines 82-89, like so:

![image](https://cloud.githubusercontent.com/assets/5608516/23529949/3c76fcda-ff65-11e6-9d09-b3fb4f48febf.png)

The $script:doctype var is only in the dev version of luckystrike.ps1

**Comment by curi0usJack** [comment]
Dangit, you found a bug. You're right, install.ps1 points to dev! argh - /me needs to learn how to git harder. Standby...

**Comment by psobject** [comment]
You're right, it points to dev. Welp.

**Comment by curi0usJack** [comment]
k. I'm pushing a fix to master for install.ps1.

To fix your install, change the vars on 87-88 to point to master, and change the $version var on 82 to be "1.1.6". Run luckystrike. It will prompt you to update. Do so, and all should be well.

**Comment by psobject** [comment]
Hehe thanks!

**Comment by curi0usJack** [comment]
np. I also fixed the install.ps1 bug in master. Thanks for logging the issue! Much appreciated. 

@psobject++
