### ISSUE TITLE
how can i bypass this error?

### ISSUE THREAD

**Issue by johntravolte** [Shellntel/luckystrike#22]
hi guys, im stuck! how can i bypass this?

![screenshot 1](https://cloud.githubusercontent.com/assets/27571315/25065388/36d6ee9c-2207-11e7-89ad-2d870988ce20.png)

thanks you

**Comment by curi0usJack** [comment]
You need to have Excel installed.

**Comment by johntravolte** [comment]
I do have Excel installed! I installed Office 2007 before installing luckystrike. I even installed them on different VMs and I get the same error message every time...
any suggestion? what should I do different?
Thank you

**Comment by curi0usJack** [comment]
I suggest moving to a more modern version of Excel. I've only tested
luckystrike on 2013+

**Comment by johntravolte** [comment]
Alright, I'll try that
Thank you

**Comment by johntravolte** [comment]
I installed Excel 2016 and I get the exact same error....
I even disabled Windows Defender
How can I make this work?
thank you
