### ISSUE TITLE
Help making similar template that it was showed in the Derbycon presentation

### ISSUE THREAD

**Issue by lizardpunk** [Shellntel/luckystrike#4]
I am trying to make a similar template but i always got this error 
![template2](https://cloud.githubusercontent.com/assets/13055051/18919806/0c130efa-8565-11e6-9a9f-26757fd2f40a.png)
![template1](https://cloud.githubusercontent.com/assets/13055051/18919815/0ed7948a-8565-11e6-9e0f-2fc124b9b0ee.png)
![template](https://cloud.githubusercontent.com/assets/13055051/18919816/0ee1ae52-8565-11e6-9314-428f7ed2b29b.png)

Some part of the code is missing and i'm not expert in visual basic, can you help me please?

**Comment by curi0usJack** [comment]
Sorry, but I'm not sure what that error says (I only speak English). Here is the macro code from the derbycon presentation:

![image](https://cloud.githubusercontent.com/assets/5608516/18920307/a0b25498-8566-11e6-92fd-756d332d6401.png)

That should be enough to get you going, but if it's a bit too much, then I suggest getting started with some basic reading about VBA: https://msdn.microsoft.com/en-us/library/office/ee814737%28v=office.14%29.aspx?f=255&MSPPError=-2147217396.

**Comment by lizardpunk** [comment]
execution error 438, thats the message
