### ISSUE TITLE
Script 1 error, MAJOR!!

### ISSUE THREAD

**Issue by onsali20** [Shellntel/luckystrike#6]
So I have all the prequsites for this program except for pssqlite, which this script is supposed to automatically install, but it justs quits in the blink of an eye after I enter the command in, luckily I got a snapshot of the response from powershell, I tried to install pssqlite for powershell v5 manually but I couldn't find any tutorial.
Help?
![screenshot_8](https://cloud.githubusercontent.com/assets/9877854/18952544/e92c8052-85fe-11e6-955d-8b5c3fee0899.png)

**Comment by curi0usJack** [comment]
You're trying to write to C:\Windows\System32 which is unfortunately the default directory for a PowerShell admin prompt. Try switching to your user's desktop & running again. 

If that doesn't work, just try running "Install-Module PSSQLite" from an admin prompt. Once that's done, rerun install.ps1.

**Comment by onsali20** [comment]
> that didnt work, the install module command in powershell does nothing but give an error meaning it doesnt do anything

**Comment by curi0usJack** [comment]
What is the error? Screenshot? If you don't give me something to work with I can't help you.

**Comment by onsali20** [comment]
> 
![screenshot_1](https://cloud.githubusercontent.com/assets/9877854/18997124/e40bfe1a-86e7-11e6-92c1-8c70759e2637.png)

**Comment by curi0usJack** [comment]
What happens if you open a powershell prompt (as administrator) and just run the following command? 

Install-Module PSSQLite

Don't run the install.ps1. Be sure that the Install-Module command works properly on your machine.

**Comment by onsali20** [comment]
> 
![screenshot_2](https://cloud.githubusercontent.com/assets/9877854/18997755/af85f328-86ea-11e6-84fd-d67e168b6b62.png)

**Comment by curi0usJack** [comment]
Run this and post the output please:

https://gist.github.com/curi0usJack/2878be90d0f2f45d728b8e8f22bb56fd

**Comment by onsali20** [comment]
http://prntscr.com/co89ue

**Comment by curi0usJack** [comment]
What does Google tell you about that error? :-)

**Comment by onsali20** [comment]
http://prntscr.com/cohr1y

**Comment by curi0usJack** [comment]
You are using Powershell v2. Per the documentation, please upgrade to PowerShell v5 (I'd also recommend going from WMF version 3 to 4 then 5).

**Comment by onsali20** [comment]
.NET Framework 4.5.2 or a later update is already installed on this computer.

**Comment by onsali20** [comment]
I also checked its the right version with the check version command

**Comment by curi0usJack** [comment]
The .Net Framework version is not the same as the Windows Management Framework version. In order for luckystrike to work, you need to have the Install-Module cmdlet available, which you don't have based on your screenshot. This generally means you don't have wmf 3 installed.
