### ISSUE TITLE
how to listen metasploit

### ISSUE THREAD

**Issue by msgthr** [Shellntel/luckystrike#7]
Hi everyone, I successfully installed and also created .xls infected file. But now my problem is how to use
Metasploit or any listening mechanism which approve and receive meterpreter connections  from infected system?

I did set the following items in luckystrike:
Target IP: 10.0.0.125 (My KALI IP address)
Target Port: 35313 (My listening port on KALI that selected in PAYLOAD setting in METASPLOIT)
Description: windows/meterpreter/reverse_tcp

Please Help me for accomplish.
Best Regards.

**Comment by curi0usJack** [comment]
This is not an issue with luckystrike. Youtube or Google would be your best resources for this.

**Comment by msgthr** [comment]
Hi sir, Unfortunately i could not find any help in google or YouTube about listening for meterpreter reception for Luckystrike. Please help if possible.
Thanks.
