### ISSUE TITLE
Eng win 7 x86, office 2013, exe can't be run by any method

### ISSUE THREAD

**Issue by notsoluckystrike** [Shellntel/luckystrike#8]
Well, running a shell command works, though no embedded exes can be launched. 
User name is 'w7_x86' (so, nothing special). Exes I embed run with no problem when launched the straight way (through cmd or by double-clicking in explorer).

**Comment by curi0usJack** [comment]
1) What infection types have you tried?
2) Does it work with any exe at all (e.g. calc.exe), or none of them?
3) How large is the .exe you are attempting to fire?
4) Is it 32 or 64bit?
5) Are you getting any errors?
6) Are you getting messages from AV?
7) Please run the following ps1 and post the output: https://gist.github.com/curi0usJack/2878be90d0f2f45d728b8e8f22bb56fd

**Comment by notsoluckystrike** [comment]
1) All three of them;
2) Tried calc.exe from system32 and putty; none of them worked (still, they are launchable by double-clicking on them in explorer);
3) < 1Mb;
4) Obviously 32 bit (os is x86);
5) Nope;
6) I'm running it on the system without av; on the same machine that generated infected .xls;
7) 
POWERSHELL VERSION:     5.0.10586.117
EXCEL VERSION:          15.0
OFFICE BITNESS:         x86
OFFICE REGKEY:          HKLM:\SOFTWARE\Microsoft\Office\15.0\Outlook
WINDOWS VERSION:        6.1.7601.65536
WINDOWS BITNESS:        32-bit
ISADMIN:                True

**Comment by curi0usJack** [comment]
Honestly, I'm not sure what to tell you. I've tested this on multiple configs, including yours, and exes always launch. Do you have group policy in place preventing execution from certain folders (%APPDATA%)? 

Please clear out %appdata%\roaming\microsoft\addins and run the SaveToDisk attack with a Putty payload. Is the exe saved to that folder? Can you run it from there?

**Comment by notsoluckystrike** [comment]
It seems the problem is gone for some reason. I diffed dropped files with original and they are equal.
Calc can't be launched in appdata (well, it runs only from system32), putty can be. Problem is solved.
