### ISSUE TITLE
detected by AV

### ISSUE THREAD

**Issue by sparta3407** [Shellntel/luckystrike#9]
hi first thanks for this job, i want to let you know that's detected by AVAST AND KASPERSKY AND NOD32, can you implement new encrypting methods!  and can you set the set the generated Exel ouput as .macro-enabled that's better than 2003 office type...thanks in advance

**Comment by curi0usJack** [comment]
Yes, Avast & Kaspersky generally detect most attacks. There are workarounds for both of them. For example, the metadata attack with your own string substitution will bypass kaspersky. That said, luckystrike was designed to bypass the majority of enterprise AV solutions that we see on pentests (Symantec, McAfee, Trend, Microsoft). Also, I would dispute that .xlsm is better than .xls. Lots of enterprises block xlsm in external emails, while xls is still allowed. That said, I'll give it some thought.

**Comment by sparta3407** [comment]
ok thanks keep up bro

2016-10-03 17:43 GMT+01:00 curi0usJack <notifications@github.com>:
